trigger:
  branches:
    include:
      - staging

pool:
  name: 'Default'
  
variables:
  buildConfiguration: 'Release'
  dotnetVersion: '10.x'
  azureServiceConnection: 'inclass-azure-service-collection'
  webAppStaging: 'inclass-staging'
  
stages:
  