<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="MediatR.Contracts" />
    <PackageReference Include="StronglyTypedId" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Common\StronglyTypedIds\*.typedid" />
  </ItemGroup>
</Project>
