// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409160723_updateDateOnlyInRegistrationPeriod")]
    partial class updateDateOnlyInRegistrationPeriod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.EducationalSystem.EducationalSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name_Ar")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_ar");

                    b.Property<string>("Name_Fr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_fr");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("educational_systems", "public");
                });

            modelBuilder.Entity("Domain.EducationalSystem.Entities.GradeCycleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BroadLevel")
                        .HasColumnType("integer")
                        .HasColumnName("broad_level");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Guid>("EducationalSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("educational_system_id");

                    b.Property<string>("Name_Ar")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_ar");

                    b.Property<string>("Name_Fr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_fr");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("EducationalSystemId");

                    b.ToTable("grade_cycle_definitions", "public");
                });

            modelBuilder.Entity("Domain.EducationalSystem.Entities.GradeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Guid>("GradeCycleDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_cycle_definition_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name_Ar")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_ar");

                    b.Property<string>("Name_Fr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name_fr");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("GradeCycleDefinitionId");

                    b.ToTable("grade_definitions", "public");
                });

            modelBuilder.Entity("Domain.File.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blob_path");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("storage_provider");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stored_file_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("stored_files", "public");
                });

            modelBuilder.Entity("Domain.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SchoolId", "TargetType", "TargetValue", "Role", "Status");

                    b.ToTable("invitations", "public");
                });

            modelBuilder.Entity("Domain.Registrations.RegistrationFormSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("base_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("GradeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_definition_id");

                    b.Property<bool>("IsCustomized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_customized");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("schema_json");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("GradeDefinitionId")
                        .HasDatabaseName("ix_registration_form_schemas_grade_definition_id");

                    b.HasIndex("SchoolId", "GradeDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_form_schemas_school_grade");

                    b.ToTable("registration_form_schemas", "public");
                });

            modelBuilder.Entity("Domain.Registrations.RegistrationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentStrategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_strategy");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<TimeOnly>("DailyCutoffTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("daily_cutoff_time");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("integer")
                        .HasColumnName("enrolled_count");

                    b.Property<Guid>("FormSchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_schema_id");

                    b.Property<Guid>("GradeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_definition_id");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_count");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("WaitlistCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("waitlist_count");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_registration_sessions_batch_id");

                    b.HasIndex("FormSchemaId")
                        .HasDatabaseName("ix_registration_sessions_form_schema_id");

                    b.HasIndex("SchoolId", "GradeDefinitionId", "Status")
                        .HasDatabaseName("ix_registration_sessions_school_grade_status");

                    b.ToTable("registration_sessions", "public");
                });

            modelBuilder.Entity("Domain.Registrations.StudentApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<Guid?>("AssignedClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FormValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_values_json");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_key");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<bool>("RescheduleUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("reschedule_used");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_first_name");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_last_name");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TargetGradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_grade_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_student_applications_parent_id");

                    b.HasIndex("SchoolId", "Status")
                        .HasDatabaseName("ix_student_applications_school_status");

                    b.HasIndex("SessionId", "Status")
                        .HasDatabaseName("ix_student_applications_session_status");

                    b.HasIndex("StudentId", "SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_applications_student_session");

                    b.ToTable("student_applications", "public");
                });

            modelBuilder.Entity("Domain.Schools.School", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ar_Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ar_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EducationalSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("educational_system_id");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GradeLevels", "Domain.Schools.School.GradeLevels#GradeLevelOffering", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Levels")
                                .HasColumnType("integer")
                                .HasColumnName("grade_levels");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EducationalSystemId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_schools_name");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_schools_owner_user_id");

                    b.ToTable("schools", "public");
                });

            modelBuilder.Entity("Domain.Schools.SchoolClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentEnrollmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_enrollment_count");

                    b.Property<Guid>("GradeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_definition_id");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_school_classes_school_id");

                    b.HasIndex("SchoolId", "GradeDefinitionId")
                        .HasDatabaseName("ix_school_classes_school_grade");

                    b.ToTable("school_classes", "public");
                });

            modelBuilder.Entity("Domain.Schools.UserSchoolMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SchoolId", "Role")
                        .IsUnique();

                    b.ToTable("user_school_memberships", "public");
                });

            modelBuilder.Entity("Domain.Students.ParentTuteur", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsLegalGuardian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legal_guardian");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_parent_tuteurs_registration_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_parent_tuteurs_school_cin");

                    b.ToTable("parent_tuteurs", "public");
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<Guid>("GradeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_definition_id");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_students_registration_id");

                    b.HasIndex("SchoolId", "GradeDefinitionId", "IsActive")
                        .HasDatabaseName("ix_students_school_grade_active");

                    b.ToTable("students", "public");
                });

            modelBuilder.Entity("Domain.Students.StudentExtendedData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_type");

                    b.Property<string>("FieldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("field_value");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("FieldKey", "FieldValue")
                        .HasDatabaseName("ix_student_extended_data_field_value");

                    b.HasIndex("StudentId", "FieldKey")
                        .IsUnique()
                        .HasDatabaseName("ix_student_extended_data_student_field");

                    b.ToTable("student_extended_data", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "public");
                });

            modelBuilder.Entity("parent_tuteur_students", b =>
                {
                    b.Property<Guid>("parent_tuteur_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("student_id")
                        .HasColumnType("uuid");

                    b.HasKey("parent_tuteur_id", "student_id");

                    b.HasIndex("student_id")
                        .HasDatabaseName("ix_parent_tuteur_students_student_id");

                    b.ToTable("parent_tuteur_students", "public");
                });

            modelBuilder.Entity("Domain.EducationalSystem.Entities.GradeCycleDefinition", b =>
                {
                    b.HasOne("Domain.EducationalSystem.EducationalSystem", null)
                        .WithMany("Cycles")
                        .HasForeignKey("EducationalSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EducationalSystem.Entities.GradeDefinition", b =>
                {
                    b.HasOne("Domain.EducationalSystem.Entities.GradeCycleDefinition", "Cycle")
                        .WithMany("Grades")
                        .HasForeignKey("GradeCycleDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("Domain.Registrations.RegistrationSession", b =>
                {
                    b.OwnsOne("SharedKernel.ValueObjects.AcademicYear", "AcademicYear", b1 =>
                        {
                            b1.Property<Guid>("RegistrationSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_end_year");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_start_year");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("academic_year_value");

                            b1.HasKey("RegistrationSessionId");

                            b1.ToTable("registration_sessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationSessionId");
                        });

                    b.OwnsOne("Domain.Registrations.ValueObjects.DailyProcessingQuota", "ProcessingQuota", b1 =>
                        {
                            b1.Property<Guid>("RegistrationSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("daily_processing_quota");

                            b1.HasKey("RegistrationSessionId");

                            b1.ToTable("registration_sessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationSessionId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Registration.RegistrationCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("RegistrationSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxSlots")
                                .HasColumnType("integer")
                                .HasColumnName("capacity_max_slots");

                            b1.HasKey("RegistrationSessionId");

                            b1.ToTable("registration_sessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationSessionId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.RegistrationPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("RegistrationSessionId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("CloseDate")
                                .HasColumnType("date")
                                .HasColumnName("period_close_date");

                            b1.Property<DateOnly>("OpenDate")
                                .HasColumnType("date")
                                .HasColumnName("period_open_date");

                            b1.HasKey("RegistrationSessionId");

                            b1.ToTable("registration_sessions", "public");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationSessionId");
                        });

                    b.OwnsMany("Domain.Registrations.ValueObjects.RegistrationPhase", "Phases", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("AllowedApplicantType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("allowed_applicant_type");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<string>("PhaseType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("phase_type");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.Property<Guid>("session_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("session_id");

                            b1.ToTable("registration_session_phases", "public");

                            b1.WithOwner()
                                .HasForeignKey("session_id");
                        });

                    b.Navigation("AcademicYear")
                        .IsRequired();

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Phases");

                    b.Navigation("ProcessingQuota");
                });

            modelBuilder.Entity("Domain.Registrations.StudentApplication", b =>
                {
                    b.OwnsOne("SharedKernel.ValueObjects.AcademicYear", "AcademicYear", b1 =>
                        {
                            b1.Property<Guid>("StudentApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_end_year");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_start_year");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("academic_year_value");

                            b1.HasKey("StudentApplicationId");

                            b1.ToTable("student_applications", "public");

                            b1.WithOwner()
                                .HasForeignKey("StudentApplicationId");
                        });

                    b.OwnsOne("Domain.Registrations.ValueObjects.QueueInfo", "QueueInfo", b1 =>
                        {
                            b1.Property<Guid>("StudentApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("queue_position");

                            b1.Property<DateOnly>("ProcessingDate")
                                .HasColumnType("date")
                                .HasColumnName("queue_processing_date");

                            b1.HasKey("StudentApplicationId");

                            b1.ToTable("student_applications", "public");

                            b1.WithOwner()
                                .HasForeignKey("StudentApplicationId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Registration.ApplicantContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("StudentApplicationId")
                                .HasColumnType("uuid");

                            b1.HasKey("StudentApplicationId");

                            b1.ToTable("student_applications", "public");

                            b1.WithOwner()
                                .HasForeignKey("StudentApplicationId");

                            b1.OwnsOne("SharedKernel.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantContactStudentApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("EmailAddress")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("contact_email");

                                    b2.HasKey("ApplicantContactStudentApplicationId");

                                    b2.ToTable("student_applications", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantContactStudentApplicationId");
                                });

                            b1.OwnsOne("SharedKernel.ValueObjects.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantContactStudentApplicationId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Number")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("contact_phone");

                                    b2.HasKey("ApplicantContactStudentApplicationId");

                                    b2.ToTable("student_applications", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantContactStudentApplicationId");
                                });

                            b1.Navigation("Email");

                            b1.Navigation("PhoneNumber");
                        });

                    b.Navigation("AcademicYear")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("QueueInfo");
                });

            modelBuilder.Entity("Domain.Schools.School", b =>
                {
                    b.HasOne("Domain.EducationalSystem.EducationalSystem", null)
                        .WithMany()
                        .HasForeignKey("EducationalSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Schools.Entities.SchoolSupportedGrade", "SupportedGrades", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid")
                                .HasColumnName("school_id");

                            b1.Property<Guid>("GradeDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("grade_definition_id");

                            b1.Property<int>("CachedBroadLevel")
                                .HasColumnType("integer")
                                .HasColumnName("cached_broad_level");

                            b1.Property<int?>("Capacity")
                                .HasColumnType("integer")
                                .HasColumnName("capacity");

                            b1.Property<bool>("IsOffered")
                                .HasColumnType("boolean")
                                .HasColumnName("is_offered");

                            b1.HasKey("SchoolId", "GradeDefinitionId");

                            b1.ToTable("school_supported_grades", "public");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Schools.SchoolContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.Property<string>("PrimaryPhoneNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("primary_phone");

                            b1.Property<string>("SecondaryPhoneNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("secondary_phone");

                            b1.HasKey("SchoolId");

                            b1.ToTable("schools", "public");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("school_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("apartment");

                            b1.Property<string>("BuildingNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("building_number");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("province");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("region");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("street_address");

                            b1.HasKey("school_id");

                            b1.ToTable("school_addresses", "public");

                            b1.WithOwner()
                                .HasForeignKey("school_id");

                            b1.OwnsOne("SharedKernel.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("Addressschool_id")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");

                                    b2.HasKey("Addressschool_id");

                                    b2.ToTable("school_addresses", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("Addressschool_id");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsMany("SharedKernel.ValueObjects.Schools.SchoolPicture", "Pictures", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("AltText")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("alt_text");

                            b1.Property<bool>("IsMain")
                                .HasColumnType("boolean")
                                .HasColumnName("is_main");

                            b1.Property<Guid>("StoredFileId")
                                .HasColumnType("uuid")
                                .HasColumnName("stored_file_id");

                            b1.Property<Guid>("school_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("school_id", "StoredFileId")
                                .IsUnique();

                            b1.ToTable("school_pictures", "public");

                            b1.WithOwner()
                                .HasForeignKey("school_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Pictures");

                    b.Navigation("SupportedGrades");
                });

            modelBuilder.Entity("Domain.Schools.SchoolClass", b =>
                {
                    b.OwnsOne("SharedKernel.ValueObjects.AcademicYear", "AcademicYear", b1 =>
                        {
                            b1.Property<Guid>("SchoolClassId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_end_year");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_start_year");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("academic_year_value");

                            b1.HasKey("SchoolClassId");

                            b1.ToTable("school_classes", "public");

                            b1.WithOwner()
                                .HasForeignKey("SchoolClassId");
                        });

                    b.OwnsOne("Domain.Schools.ValueObjects.ClassCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("SchoolClassId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxStudents")
                                .HasColumnType("integer")
                                .HasColumnName("capacity_max_students");

                            b1.HasKey("SchoolClassId");

                            b1.ToTable("school_classes", "public");

                            b1.WithOwner()
                                .HasForeignKey("SchoolClassId");
                        });

                    b.OwnsOne("Domain.Schools.ValueObjects.ClassName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SchoolClassId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("name");

                            b1.HasKey("SchoolClassId");

                            b1.ToTable("school_classes", "public");

                            b1.WithOwner()
                                .HasForeignKey("SchoolClassId");
                        });

                    b.Navigation("AcademicYear")
                        .IsRequired();

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Students.ParentTuteur", b =>
                {
                    b.OwnsOne("SharedKernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ParentTuteurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_apartment");

                            b1.Property<string>("BuildingNumber")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_building_number");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_province");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_region");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("address_street");

                            b1.HasKey("ParentTuteurId");

                            b1.ToTable("parent_tuteurs", "public");

                            b1.WithOwner()
                                .HasForeignKey("ParentTuteurId");

                            b1.OwnsOne("SharedKernel.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("AddressParentTuteurId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasPrecision(10, 7)
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_latitude");

                                    b2.Property<double>("Longitude")
                                        .HasPrecision(10, 7)
                                        .HasColumnType("double precision")
                                        .HasColumnName("address_longitude");

                                    b2.HasKey("AddressParentTuteurId");

                                    b2.ToTable("parent_tuteurs", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressParentTuteurId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ParentTuteurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.HasKey("ParentTuteurId");

                            b1.ToTable("parent_tuteurs", "public");

                            b1.WithOwner()
                                .HasForeignKey("ParentTuteurId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("ParentTuteurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("ParentTuteurId");

                            b1.ToTable("parent_tuteurs", "public");

                            b1.WithOwner()
                                .HasForeignKey("ParentTuteurId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("ParentTuteurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_number");

                            b1.HasKey("ParentTuteurId");

                            b1.ToTable("parent_tuteurs", "public");

                            b1.WithOwner()
                                .HasForeignKey("ParentTuteurId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.PhoneNumber", "SecondaryPhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("ParentTuteurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("secondary_phone_number");

                            b1.HasKey("ParentTuteurId");

                            b1.ToTable("parent_tuteurs", "public");

                            b1.WithOwner()
                                .HasForeignKey("ParentTuteurId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.MoroccanCin", "CIN", b1 =>
                        {
                            b1.Property<Guid>("ParentTuteurId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("cin");

                            b1.HasKey("ParentTuteurId");

                            b1.ToTable("parent_tuteurs", "public");

                            b1.WithOwner()
                                .HasForeignKey("ParentTuteurId");
                        });

                    b.Navigation("Address");

                    b.Navigation("CIN")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("SecondaryPhoneNumber");
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.OwnsOne("SharedKernel.ValueObjects.AcademicYear", "AcademicYear", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EndYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_end_year");

                            b1.Property<int>("StartYear")
                                .HasColumnType("integer")
                                .HasColumnName("academic_year_start_year");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("academic_year_value");

                            b1.HasKey("StudentId");

                            b1.ToTable("students", "public");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("StudentId");

                            b1.ToTable("students", "public");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("SharedKernel.ValueObjects.Registration.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("national_id_type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("national_id_value");

                            b1.HasKey("StudentId");

                            b1.ToTable("students", "public");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("AcademicYear")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("NationalId");
                });

            modelBuilder.Entity("parent_tuteur_students", b =>
                {
                    b.HasOne("Domain.Students.ParentTuteur", null)
                        .WithMany()
                        .HasForeignKey("parent_tuteur_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_tuteur_students_parent_tuteur_id");

                    b.HasOne("Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_tuteur_students_student_id");
                });

            modelBuilder.Entity("Domain.EducationalSystem.EducationalSystem", b =>
                {
                    b.Navigation("Cycles");
                });

            modelBuilder.Entity("Domain.EducationalSystem.Entities.GradeCycleDefinition", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
